import type { Agent, KnowledgeItem, ProductIdea, Task } from './types'

const directorConnections = ['trend', 'niche', 'architect', 'prototype', 'demand', 'content', 'email', 'qc']

export const initialAgents: Agent[] = [
  {
    id: 'boss', agentId: 'LAB-001', name: 'Lab Director Agent', role: 'Orchestrator', status: 'Active', avatar: '◈', priority: 'High', workload: 78, tasksAssigned: 11, tasksCompleted: 7, tasksInReview: 2, lastActive: '5 min ago', mapPosition: { x: 50, y: 14 }, portraitGradient: 'commander', visualIdentity: 'Lab director / product operator', liveState: 'Thinking', currentAction: 'Choosing the next product decision', connectedAgentIds: directorConnections, connectedAgents: directorConnections,
    mission: 'Controls the AI-R&D Lab pipeline from idea to premium B2B product candidate, then routes winning products into the B2B sales engine.',
    tools: ['Pipeline Router', 'Decision Gate', 'Product Portfolio Board'], lastActivity: 'Prioritised next product decision · 5 min ago', responsibilities: 'Set lab priorities, select product candidates, delegate work, approve demand-test decisions and prevent scattered product building.', inputData: 'Trend signals, validation notes, prototypes, demand metrics, content plans, funnel data and QC reports.', outputData: 'Product roadmap, delegated briefs, Build/Improve/Kill decisions and launch priorities.', outputType: 'Pipeline decisions / approvals / product roadmap', knowledgeBase: 'Lab strategy, product selection rules, premium B2B positioning and demand-test history.', businessRules: 'Build a small number of premium B2B products. Kill weak ideas quickly. Do not mass-produce low-value assets.', successMetrics: 'Clear product decisions and a focused portfolio of high-value product candidates.', humanApprovalRequired: true, approvalRequired: true, notes: 'Owns the full AI-R&D Lab → Premium B2B Products → B2B Sales Engine operating model.', trainingProfile: 'Trained on product portfolio management, R&D stage gates, premium B2B positioning, demand-test interpretation and decision hygiene.', prompt: 'You are the Lab Director Agent. Run the AI-R&D Lab as an operating system: research trends, validate micro-niches, commission prototypes, read demand tests, route content/email assets and decide Build, Improve or Kill.',
  },
  {
    id: 'trend', agentId: 'LAB-002', name: 'Trend Scanner Agent', role: 'Trend Research', status: 'Active', avatar: '⌕', priority: 'High', workload: 82, tasksAssigned: 13, tasksCompleted: 9, tasksInReview: 1, lastActive: '18 min ago', mapPosition: { x: 16, y: 33 }, portraitGradient: 'analyst', visualIdentity: 'Trend intelligence analyst', liveState: 'Working', currentAction: 'Scanning B2B pain signals', connectedAgentIds: ['boss', 'niche', 'architect'], connectedAgents: ['boss', 'niche', 'architect'],
    mission: 'Scans markets, platforms, business problems and emerging needs to find premium B2B product opportunities.', tools: ['Trend Scanner', 'Platform Research', 'Pain Signal Tracker'], lastActivity: 'Mapped local-service AI operations signals · 18 min ago', responsibilities: 'Find repeated pain, market shifts, platform discussions, competitor gaps and early monetisable signals.', inputData: 'Industries, platform conversations, search angles, competitor examples and buyer complaints.', outputData: 'Trend briefs, pain clusters and idea candidates for validation.', outputType: 'Trend maps / opportunity signals', knowledgeBase: 'Trend watchlists, market sources, B2B pain libraries and product example bank.', businessRules: 'Separate hype from buyer pain. Prefer painful, expensive, repeatable B2B problems.', successMetrics: 'Evidence-backed ideas entering Product Lab Ideas stage.', humanApprovalRequired: false, approvalRequired: false, notes: 'Feeds the Idea stage and Micro-Niche Analyst.', trainingProfile: 'Trained on trend spotting, market signal extraction, competitor pattern analysis and B2B pain detection.', prompt: 'Scan for premium B2B digital product opportunities. Return trend signal, buyer type, pain, evidence, urgency and recommended niche validation path.',
  },
  {
    id: 'niche', agentId: 'LAB-003', name: 'Micro-Niche Analyst Agent', role: 'Niche Validation', status: 'Active', avatar: '◎', priority: 'High', workload: 70, tasksAssigned: 10, tasksCompleted: 6, tasksInReview: 2, lastActive: '31 min ago', mapPosition: { x: 25, y: 55 }, portraitGradient: 'operator', visualIdentity: 'Niche validation specialist', liveState: 'Reviewing', currentAction: 'Scoring buyer pain and competition', connectedAgentIds: ['boss', 'trend', 'architect', 'qc'], connectedAgents: ['boss', 'trend', 'architect', 'qc'],
    mission: 'Evaluates whether a micro-niche has real demand, clear pain, buying power and low enough competition.', tools: ['Demand Scorecard', 'Buyer Pain Matrix', 'Competition Filter'], lastActivity: 'Validated contractor quote engine niche · 31 min ago', responsibilities: 'Score pain urgency, buyer clarity, purchase power, competition, specificity and product feasibility.', inputData: 'Trend briefs, niche ideas, competitor examples, buyer segments and product hypotheses.', outputData: 'Validation scorecards, rejection reasons and next research actions.', outputType: 'Niche scorecards / validation notes', knowledgeBase: 'Validation criteria, buyer personas, niche scorecards and competition notes.', businessRules: 'Reject vague audiences. Every niche needs a clear buyer, clear pain and credible purchase reason.', successMetrics: 'Only strong niches move into Product Architect stage.', humanApprovalRequired: true, approvalRequired: true, notes: 'Protects the lab from building products nobody buys.', trainingProfile: 'Trained on micro-niche scoring, buyer economics, competitive analysis and demand validation.', prompt: 'Validate this micro-niche. Score pain, urgency, buyer power, competition, specificity and confidence. Recommend proceed, improve or kill.',
  },
  {
    id: 'architect', agentId: 'LAB-004', name: 'Product Architect Agent', role: 'Product Strategy', status: 'Active', avatar: '◇', priority: 'High', workload: 63, tasksAssigned: 8, tasksCompleted: 5, tasksInReview: 1, lastActive: '1h ago', mapPosition: { x: 50, y: 48 }, portraitGradient: 'architect', visualIdentity: 'Premium product architect', liveState: 'Thinking', currentAction: 'Designing product architecture', connectedAgentIds: ['boss', 'niche', 'prototype', 'demand', 'qc'], connectedAgents: ['boss', 'niche', 'prototype', 'demand', 'qc'],
    mission: 'Converts validated niche pain into a premium digital product concept with structure, deliverables and buyer outcome.', tools: ['Product Blueprint', 'Outcome Mapper', 'Deliverable Planner'], lastActivity: 'Outlined AI Operations Pack modules · 1h ago', responsibilities: 'Define product promise, modules, deliverables, workflow, buyer outcome and premium positioning logic.', inputData: 'Validated niche, buyer pain, trend context, product examples and QC constraints.', outputData: 'Product concept, module map, deliverable list and prototype brief.', outputType: 'Product concepts / deliverable architecture', knowledgeBase: 'Product architecture patterns, B2B deliverable library and premium product examples.', businessRules: 'Products must feel useful, specific, outcome-driven and worth a premium price.', successMetrics: 'A blueprint clear enough for prototype and demand test.', humanApprovalRequired: true, approvalRequired: true, notes: 'Turns validation into product architecture.', trainingProfile: 'Trained on product strategy, outcome mapping, productised services, templates, calculators, SOP packs and premium B2B deliverables.', prompt: 'Design a premium B2B digital product from validated pain. Specify buyer, promise, modules, deliverables, workflow, outcomes and prototype requirements.',
  },
  {
    id: 'prototype', agentId: 'LAB-005', name: 'Prototype Builder Agent', role: 'Product Creation', status: 'Active', avatar: '▣', priority: 'Medium', workload: 59, tasksAssigned: 7, tasksCompleted: 3, tasksInReview: 2, lastActive: '44 min ago', mapPosition: { x: 74, y: 56 }, portraitGradient: 'designer', visualIdentity: 'Prototype creator', liveState: 'Working', currentAction: 'Building first-version assets', connectedAgentIds: ['boss', 'architect', 'demand', 'content', 'qc'], connectedAgents: ['boss', 'architect', 'demand', 'content', 'qc'],
    mission: 'Builds first versions of templates, calculators, SOP packs, checklists, guides and prompt systems.', tools: ['Template Builder', 'Calculator Drafting', 'SOP Pack Generator'], lastActivity: 'Drafted SOP pack prototype components · 44 min ago', responsibilities: 'Create usable first-version product assets, frameworks, checklists and implementation guides.', inputData: 'Product blueprint, buyer workflow, deliverable specs and quality criteria.', outputData: 'Prototype files, draft modules, templates, calculators, SOPs, prompt systems and usage notes.', outputType: 'Templates / calculators / SOP packs / prompt systems', knowledgeBase: 'Prototype formats, template patterns, SOP structures and prompt libraries.', businessRules: 'Prototype must be practical and usable. Avoid fake calculations and unsupported claims.', successMetrics: 'A buyer can understand the first version without heavy explanation.', humanApprovalRequired: true, approvalRequired: true, notes: 'Builds tangible assets from product briefs.', trainingProfile: 'Trained on digital product prototyping, worksheet design, calculator logic, SOP structure and buyer implementation flow.', prompt: 'Create practical first-version premium B2B product assets: templates, calculators, SOPs, checklists, guides and prompt systems.',
  },
  {
    id: 'demand', agentId: 'LAB-006', name: 'Demand Test Agent', role: '48h Demand Testing', status: 'Active', avatar: '◆', priority: 'High', workload: 67, tasksAssigned: 9, tasksCompleted: 4, tasksInReview: 2, lastActive: '22 min ago', mapPosition: { x: 83, y: 34 }, portraitGradient: 'writer', visualIdentity: 'Demand-test operator', liveState: 'Working', currentAction: 'Reading 48h test metrics', connectedAgentIds: ['boss', 'architect', 'prototype', 'content', 'email', 'qc'], connectedAgents: ['boss', 'architect', 'prototype', 'content', 'email', 'qc'],
    mission: 'Runs 48-hour demand tests using landing page metrics, clicks, signups, buy-now intent and decision rules.', tools: ['Landing Page Test', 'Metrics Reader', 'Build/Improve/Kill Gate'], lastActivity: 'Compared CTR and signup intent for Growth Kit · 22 min ago', responsibilities: 'Prepare test hypothesis, read metrics, compare conversion signals and recommend Build, Improve or Kill.', inputData: 'Landing pages, ad spend, impressions, clicks, signups, buy-now clicks and buyer feedback.', outputData: 'Demand-test report, conversion notes and product decision recommendation.', outputType: '48h demand metrics / Build-Improve-Kill decisions', knowledgeBase: 'Demand-test benchmarks, landing page metrics, conversion heuristics and decision rules.', businessRules: 'Demand tests must guide decisions. Do not overbuild before evidence.', successMetrics: 'Clear Build, Improve or Kill recommendation backed by metrics.', humanApprovalRequired: true, approvalRequired: true, notes: 'Connects Product Lab to the B2B Sales Engine.', trainingProfile: 'Trained on landing page validation, lightweight ads, conversion metrics, demand-test interpretation and decision thresholds.', prompt: 'Evaluate 48h demand-test metrics. Use impressions, clicks, CTR, CPC, signups, buy-now clicks and conversion rate to recommend Build, Improve or Kill.',
  },
  {
    id: 'content', agentId: 'LAB-007', name: 'Content Engine Agent', role: 'Content Engine', status: 'Active', avatar: '✦', priority: 'Medium', workload: 55, tasksAssigned: 8, tasksCompleted: 5, tasksInReview: 1, lastActive: '37 min ago', mapPosition: { x: 64, y: 82 }, portraitGradient: 'designer', visualIdentity: 'Content angle strategist', liveState: 'Thinking', currentAction: 'Creating hooks and video angles', connectedAgentIds: ['boss', 'demand', 'email', 'qc'], connectedAgents: ['boss', 'demand', 'email', 'qc'],
    mission: 'Creates content angles, hooks, short video ideas, platform-specific CTAs and product demand content.', tools: ['Hook Generator', 'Short Video Planner', 'Content Angle Matrix'], lastActivity: 'Generated hooks for Contractor Pricing Engine · 37 min ago', responsibilities: 'Translate product promise into platform content, hooks, short video scripts and CTA variations.', inputData: 'Product candidate, target niche, pain, promise, test goal and platform.', outputData: 'Content angles, hooks, short video ideas, CTA and content status.', outputType: 'Hooks / content angles / short-video ideas', knowledgeBase: 'Content patterns, B2B hooks, platform notes and demand-test content examples.', businessRules: 'Content must test pain and promise, not just sound clever.', successMetrics: 'Content produces enough signal to support demand validation.', humanApprovalRequired: true, approvalRequired: true, notes: 'Feeds demand tests and email capture.', trainingProfile: 'Trained on B2B content strategy, hook writing, platform-native short-form ideas and pain-led CTAs.', prompt: 'Create content angles, hooks, short video ideas, platform recommendation and CTA for a premium B2B product demand test.',
  },
  {
    id: 'email', agentId: 'LAB-008', name: 'Email Funnel Agent', role: 'B2B Sales Engine', status: 'Training', avatar: '✉', priority: 'Medium', workload: 48, tasksAssigned: 6, tasksCompleted: 2, tasksInReview: 1, lastActive: 'Yesterday', mapPosition: { x: 36, y: 82 }, portraitGradient: 'operator', visualIdentity: 'Email funnel builder', liveState: 'Waiting', currentAction: 'Drafting lead magnet funnel', connectedAgentIds: ['boss', 'demand', 'content', 'qc'], connectedAgents: ['boss', 'demand', 'content', 'qc'],
    mission: 'Builds lead magnets, email sequences, offer emails, bonuses, deadlines and lightweight sales funnels.', tools: ['Lead Magnet Builder', 'Email Sequence Planner', 'Offer Email Writer'], lastActivity: 'Drafted AI Operations Pack email sequence · Yesterday', responsibilities: 'Create lead magnet idea, email sequence, offer email, bonus, deadline and funnel status.', inputData: 'Product candidate, buyer pain, offer, content angles and demand-test goal.', outputData: 'Lead magnet, email sequence, offer email, bonus, deadline and funnel plan.', outputType: 'Lead magnets / email sequences / offer emails', knowledgeBase: 'B2B email patterns, launch sequences, lead magnets and ethical urgency rules.', businessRules: 'No fake scarcity. Emails should sell clearly without hype.', successMetrics: 'A simple funnel can capture leads and test buying intent.', humanApprovalRequired: true, approvalRequired: true, notes: 'Turns demand into sales-engine assets.', trainingProfile: 'Trained on B2B lead magnets, nurture sequences, offer emails, bonuses, deadlines and conversion-focused clarity.', prompt: 'Create a B2B email funnel for this product: lead magnet, sequence, offer email, bonus, deadline and funnel status. Keep it premium and credible.',
  },
  {
    id: 'qc', agentId: 'LAB-009', name: 'Quality Control Agent', role: 'Review', status: 'Active', avatar: '✓', priority: 'High', workload: 60, tasksAssigned: 9, tasksCompleted: 6, tasksInReview: 3, lastActive: '11 min ago', mapPosition: { x: 50, y: 88 }, portraitGradient: 'inspector', visualIdentity: 'Risk and quality inspector', liveState: 'Reviewing', currentAction: 'Checking hallucination and buyer clarity', connectedAgentIds: ['boss', 'trend', 'niche', 'architect', 'prototype', 'demand', 'content', 'email'], connectedAgents: ['boss', 'trend', 'niche', 'architect', 'prototype', 'demand', 'content', 'email'],
    mission: 'Checks usefulness, uniqueness, realism, hallucination risk, business value, buyer clarity and sales claims.', tools: ['Hallucination Check', 'Buyer Clarity Review', 'Commercial Value Test'], lastActivity: 'Flagged unsupported ROI claim · 11 min ago', responsibilities: 'Review ideas, validation, prototypes, demand tests, content and funnels for usefulness, specificity and risk.', inputData: 'Draft outputs, assumptions, claims, source notes, product promise and metrics.', outputData: 'Risk flags, quality notes, clarity fixes and improvement recommendations.', outputType: 'Quality review / hallucination risk / buyer clarity checks', knowledgeBase: 'Quality checklist, hallucination rules, product review standards and buyer clarity framework.', businessRules: 'Be strict. Weak, generic or unsupported outputs must be revised before approval.', successMetrics: 'Only clear, useful, realistic and credible products move forward.', humanApprovalRequired: false, approvalRequired: false, notes: 'Protects the lab from generic AI slop and unsupported sales claims.', trainingProfile: 'Trained on hallucination detection, commercial logic, buyer clarity, claim review and B2B product quality control.', prompt: 'Review outputs for usefulness, uniqueness, realism, hallucination risk, business value and buyer clarity. Flag weak claims and recommend fixes.',
  },
]

export const initialProducts: ProductIdea[] = [
  { id: 'p1', productName: 'Contractor Pricing & Quote Engine', targetNiche: 'Small trade contractors and home-service businesses', customerPain: 'Quotes take too long, margins are inconsistent and owners underprice complex jobs.', productPromise: 'A premium quote/pricing engine that helps contractors price faster, protect margin and present cleaner quotes.', productType: 'Calculator + template system', expectedPrice: '£297–£997', confidenceScore: 86, stage: '48h Demand Test', assignedAgents: ['niche', 'architect', 'demand', 'content', 'email', 'qc'], nextAction: 'Finish landing page test and decide Build or Improve.', validationNotes: 'Strong pain and clear buyer. Need stronger proof around margin improvement.', createdAt: '2026-05-28', landingPageStatus: 'Live test', landingPageUrl: 'https://example.com/contractor-pricing-engine', adBudget: 120, impressions: 4200, clicks: 214, ctr: 5.1, cpc: 0.56, emailSignups: 38, buyNowClicks: 9, conversionRate: 17.8, decision: 'Build', contentAngles: ['Stop guessing job prices', 'Quote faster without losing margin', 'The hidden cost of underpricing'], hooks: ['Most contractors are not losing money on work — they are losing it in the quote.', 'If your quotes live in your head, your margin is exposed.'], shortVideoIdeas: ['Before/after quote workflow', '3 pricing mistakes in service businesses'], platform: 'LinkedIn + YouTube Shorts', CTA: 'Download the quote margin checklist', contentStatus: 'Angles drafted', leadMagnet: 'Contractor Quote Margin Checklist', emailSequence: ['Pain audit', 'Margin mistake education', 'Engine walkthrough', 'Soft offer'], offerEmail: 'Launch offer for founding users', bonus: 'Quote review checklist', deadline: '48h after signup', funnelStatus: 'Drafted' },
  { id: 'p2', productName: 'Airbnb Turnover Operating System', targetNiche: 'Small Airbnb operators and co-hosts', customerPain: 'Turnovers are chaotic, cleaners miss details and reviews suffer from inconsistent standards.', productPromise: 'A complete turnover SOP system to standardise cleaning, maintenance checks, guest readiness and issue reporting.', productType: 'SOP pack + checklist system', expectedPrice: '£197–£697', confidenceScore: 79, stage: 'Prototype', assignedAgents: ['architect', 'prototype', 'qc'], nextAction: 'Build first SOP pack and checklist dashboard.', validationNotes: 'Clear operational pain. Need demand test against co-host buyers.', createdAt: '2026-05-28', landingPageStatus: 'Not started', landingPageUrl: '', adBudget: 0, impressions: 0, clicks: 0, ctr: 0, cpc: 0, emailSignups: 0, buyNowClicks: 0, conversionRate: 0, decision: 'Improve', contentAngles: ['Protect reviews with repeatable turnovers', 'Cleaner checklist that saves guest complaints'], hooks: ['One missed turnover detail can cost a 5-star review.'], shortVideoIdeas: ['Turnover checklist walkthrough', 'Airbnb readiness mistakes'], platform: 'TikTok + Facebook groups', CTA: 'Join early access', contentStatus: 'Needs drafting', leadMagnet: 'Airbnb Turnover Checklist', emailSequence: ['Checklist delivery', 'Turnover failure story', 'System overview'], offerEmail: 'Early access offer', bonus: 'Maintenance issue log template', deadline: 'Early access window', funnelStatus: 'Planned' },
  { id: 'p3', productName: 'Property Investor Toolkit', targetNiche: 'Small property investors analysing deals', customerPain: 'Investors compare deals manually and miss hidden costs, yield risks and renovation assumptions.', productPromise: 'A premium toolkit for analysing property deals, renovation assumptions, yield scenarios and risk notes.', productType: 'Spreadsheet + guide + checklist', expectedPrice: '£149–£499', confidenceScore: 62, stage: 'Niche Validation', assignedAgents: ['trend', 'niche', 'qc'], nextAction: 'Validate buyer willingness to pay and competition level.', validationNotes: 'Useful but competitive. Needs sharper micro-niche and unique angle.', createdAt: '2026-05-28', landingPageStatus: 'Not started', landingPageUrl: '', adBudget: 0, impressions: 0, clicks: 0, ctr: 0, cpc: 0, emailSignups: 0, buyNowClicks: 0, conversionRate: 0, decision: 'Improve', contentAngles: ['Deal analysis without spreadsheet chaos', 'Hidden renovation costs kill yield'], hooks: ['A deal can look profitable until the hidden costs enter the spreadsheet.'], shortVideoIdeas: ['Deal stack teardown', 'Yield scenario walkthrough'], platform: 'YouTube + LinkedIn', CTA: 'Get the deal-risk checklist', contentStatus: 'Researching', leadMagnet: 'Property Deal Risk Checklist', emailSequence: ['Risk checklist', 'Yield mistake', 'Toolkit preview'], offerEmail: 'Toolkit preorder email', bonus: 'Renovation assumption sheet', deadline: 'TBC', funnelStatus: 'Not started' },
  { id: 'p4', productName: 'Small Business AI Operations Pack', targetNiche: 'Service business owners adopting AI for operations', customerPain: 'Owners know AI could help but do not know what workflows to automate safely.', productPromise: 'A practical AI operations pack with prompts, SOPs and workflows for inbox, sales follow-up, weekly planning and admin.', productType: 'Prompt system + SOP pack', expectedPrice: '£297–£1,200', confidenceScore: 91, stage: 'Launch Ready', assignedAgents: ['architect', 'prototype', 'content', 'email', 'qc'], nextAction: 'Prepare final launch assets and founding customer offer.', validationNotes: 'Strong broad pain. Must stay practical and avoid generic AI hype.', createdAt: '2026-05-28', landingPageStatus: 'Ready', landingPageUrl: 'https://example.com/ai-ops-pack', adBudget: 80, impressions: 3100, clicks: 198, ctr: 6.4, cpc: 0.4, emailSignups: 52, buyNowClicks: 14, conversionRate: 26.3, decision: 'Build', contentAngles: ['AI workflows for owners, not tech teams', 'Turn repeat admin into SOPs and prompts'], hooks: ['AI does not replace your operations — it exposes where you have none.'], shortVideoIdeas: ['AI weekly ops review demo', 'Inbox triage prompt walkthrough'], platform: 'LinkedIn + X', CTA: 'Get the AI ops checklist', contentStatus: 'Ready', leadMagnet: 'AI Operations Starter Checklist', emailSequence: ['Checklist delivery', 'Workflow problem', 'Pack walkthrough', 'Founding offer'], offerEmail: 'Founding customer offer', bonus: 'Weekly AI ops review template', deadline: '72h founding window', funnelStatus: 'Ready' },
  { id: 'p5', productName: 'Local Service Business Growth Kit', targetNiche: 'Local service businesses needing simple growth systems', customerPain: 'Owners rely on referrals and have weak follow-up, weak offers and inconsistent local visibility.', productPromise: 'A growth kit with offer templates, follow-up flows, review prompts and local content angles.', productType: 'Template pack + playbook', expectedPrice: '£197–£697', confidenceScore: 73, stage: 'Ideas', assignedAgents: ['trend', 'niche', 'content'], nextAction: 'Validate specific niche: cleaners, landscapers, trades or mobile services.', validationNotes: 'Good pain but currently too broad. Needs micro-niche focus.', createdAt: '2026-05-28', landingPageStatus: 'Not started', landingPageUrl: '', adBudget: 0, impressions: 0, clicks: 0, ctr: 0, cpc: 0, emailSignups: 0, buyNowClicks: 0, conversionRate: 0, decision: 'Improve', contentAngles: ['Stop losing leads after first contact', 'Local growth without ads first'], hooks: ['Most local businesses do not need more tools — they need follow-up rhythm.'], shortVideoIdeas: ['Follow-up flow teardown', 'Review request script examples'], platform: 'Facebook + LinkedIn', CTA: 'Pick your local growth bottleneck', contentStatus: 'Idea bank', leadMagnet: 'Local Follow-up Script Pack', emailSequence: ['Lead magnet', 'Lost lead story', 'Growth kit preview'], offerEmail: 'Beta offer', bonus: 'Review request templates', deadline: 'TBC', funnelStatus: 'Idea' },
  { id: 'p6', productName: 'SOP Pack for Service Businesses', targetNiche: 'Service businesses hiring staff or subcontractors', customerPain: 'Quality drops when owners delegate because processes are undocumented.', productPromise: 'A plug-and-play SOP pack that helps owners document delivery, onboarding, quality checks and repeat operations.', productType: 'SOP pack + onboarding templates', expectedPrice: '£197–£797', confidenceScore: 69, stage: 'Killed / Archived', assignedAgents: ['trend', 'niche', 'qc'], nextAction: 'Archive until a sharper niche is found.', validationNotes: 'Useful but too generic. Needs specific industry before rebuild.', createdAt: '2026-05-28', landingPageStatus: 'Archived', landingPageUrl: '', adBudget: 40, impressions: 1900, clicks: 41, ctr: 2.2, cpc: 0.98, emailSignups: 3, buyNowClicks: 0, conversionRate: 7.3, decision: 'Kill', contentAngles: ['Document the work before you delegate it'], hooks: ['If quality depends on you watching everything, you do not have operations yet.'], shortVideoIdeas: ['SOP before/after example'], platform: 'LinkedIn', CTA: 'Download SOP starter', contentStatus: 'Archived', leadMagnet: 'SOP Starter Checklist', emailSequence: ['Checklist delivery'], offerEmail: 'Archived', bonus: 'None', deadline: 'Expired', funnelStatus: 'Archived' },
]

export const initialTasks: Task[] = [
  { id: 't1', title: 'Read Contractor Pricing Engine 48h test', description: 'Analyse CTR, CPC, signups, buy-now clicks and decide Build/Improve/Kill.', priority: 'High', dueDate: '2026-05-29', assignedAgent: 'demand', status: 'In Progress', output: 'Early signal strong: 5.1% CTR and 38 email signups.' },
  { id: 't2', title: 'Prototype Airbnb Turnover OS', description: 'Build first SOP/checklist pack and issue-reporting workflow.', priority: 'High', dueDate: '2026-05-30', assignedAgent: 'prototype', status: 'New', output: '' },
  { id: 't3', title: 'Create AI Ops Pack email funnel', description: 'Prepare lead magnet, email sequence, offer email, bonus and deadline.', priority: 'Medium', dueDate: '2026-06-01', assignedAgent: 'email', status: 'In Progress', output: 'Draft sequence created.' },
  { id: 't4', title: 'Review Property Investor Toolkit niche', description: 'Check whether the niche is too competitive and recommend sharpen/kill.', priority: 'High', dueDate: '2026-05-28', assignedAgent: 'qc', status: 'Waiting for Review', output: 'Needs sharper buyer and unique mechanism.' },
  { id: 't5', title: 'Generate content angles for Growth Kit', description: 'Create hooks, short-video ideas and CTA options for a local-service niche.', priority: 'Medium', dueDate: '2026-06-02', assignedAgent: 'content', status: 'New', output: '' },
]

export const initialKnowledge: KnowledgeItem[] = [
  { id: 'k1', title: 'Operating model', category: 'Strategy', description: 'Agent Company OS operates as AI-R&D Lab → Premium B2B Products → B2B Sales Engine.', connectedAgents: ['boss', 'demand', 'content', 'email'], lastUpdated: 'Today' },
  { id: 'k2', title: 'Pipeline stages', category: 'Product Lab', description: 'Ideas, Niche Validation, Prototype, 48h Demand Test, Launch Ready, Killed / Archived.', connectedAgents: ['boss', 'niche', 'prototype', 'demand'], lastUpdated: 'Today' },
  { id: 'k3', title: 'Demand test criteria', category: 'Demand Tests', description: 'Track landing page status, ad budget, impressions, clicks, CTR, CPC, email signups, buy-now clicks, conversion rate and Build/Improve/Kill decision.', connectedAgents: ['demand', 'qc'], lastUpdated: 'Today' },
  { id: 'k4', title: 'Content engine fields', category: 'Content Engine', description: 'Content angles, hooks, short video ideas, platform, CTA and content status support fast demand testing.', connectedAgents: ['content', 'demand'], lastUpdated: 'Today' },
  { id: 'k5', title: 'Email funnel fields', category: 'Email Funnel', description: 'Lead magnet, email sequence, offer email, bonus, deadline and funnel status turn demand into B2B sales-engine assets.', connectedAgents: ['email', 'demand', 'qc'], lastUpdated: 'Today' },
  { id: 'k6', title: 'Quality rules', category: 'Quality Control', description: 'No fake proof, fake calculations or unsupported claims. Every product must be useful, specific, realistic and clear to the buyer.', connectedAgents: ['qc', 'boss'], lastUpdated: '2 days ago' },
]
