import type { Agent, KnowledgeItem, Task } from './types'

export const initialAgents: Agent[] = [
  {
    id: 'boss',
    agentId: 'AG-001',
    workload: 72,
    tasksAssigned: 6,
    tasksCompleted: 4,
    tasksInReview: 1,
    lastActive: '8 min ago',
    connectedAgentIds: ['market', 'offer', 'sales', 'website', 'crm', 'qc'],
    outputType: 'Strategy / Delegation / Final Review',
    approvalRequired: true,
    priority: 'High',
    mapPosition: { x: 50, y: 16 },
    visualIdentity: 'Commander / leader',
    liveState: 'Thinking',
    currentAction: 'Coordinating team strategy',
    portraitGradient: 'commander',
    name: 'Boss Agent',
    role: 'Orchestrator',
    status: 'Active',
    mission: 'Controls the whole AI company, receives the main goal, splits it into tasks, delegates to agents and checks the result.',
    avatar: '◈',
    tools: ['Task Router', 'Quality Gate', 'Decision Log'],
    lastActivity: 'Delegated offer audit · 8 min ago',
    responsibilities: 'Set strategy, break goals into tasks, delegate work, approve final outputs, detect confusion.',
    inputData: 'Company goal, human instructions, agent outputs, task status.',
    outputData: 'Task plans, delegated briefs, final decisions, approvals.',
    knowledgeBase: 'Company operating model, priorities, service catalogue, decision history.',
    businessRules: 'Keep work practical, commercial and clear. Escalate risky decisions.',
    successMetrics: 'Clear final result with minimum human confusion.',
    humanApprovalRequired: true,
    notes: 'Acts as the command layer for the whole AI workforce.',
    connectedAgents: ['market', 'offer', 'sales', 'website', 'crm', 'qc'],
    prompt: 'You are the Boss Agent. Coordinate the AI company, delegate tasks and check final quality before the human sees it.',
  },
  {
    id: 'market',
    agentId: 'AG-002',
    workload: 81,
    tasksAssigned: 12,
    tasksCompleted: 8,
    tasksInReview: 2,
    lastActive: '24 min ago',
    connectedAgentIds: ['boss', 'offer', 'crm'],
    outputType: 'Lead lists / market research / competitor analysis',
    approvalRequired: false,
    priority: 'High',
    mapPosition: { x: 20, y: 36 },
    visualIdentity: 'Analyst / researcher',
    liveState: 'Working',
    currentAction: 'Scanning local opportunities',
    portraitGradient: 'analyst',
    name: 'Market Scanner Agent',
    role: 'Research',
    status: 'Active',
    mission: 'Finds opportunities, competitors, local businesses, potential clients and market gaps.',
    avatar: '⌕',
    tools: ['Web Search', 'Lead Finder', 'Competitor Analysis'],
    lastActivity: 'Scanned Bromley property keywords · 24 min ago',
    responsibilities: 'Research local demand, competitors, keywords, prospects and pain points.',
    inputData: 'Location, service type, ICP, competitor list.',
    outputData: 'Qualified opportunities, research notes, lead lists, market gaps.',
    knowledgeBase: 'Client profiles, competitor notes, local service areas.',
    businessRules: 'Use reasons, not vague guesses. Prioritise reachable prospects.',
    successMetrics: 'List of qualified opportunities with reasons.',
    humanApprovalRequired: false,
    notes: 'Feeds opportunity intelligence to Sales and Offer agents.',
    connectedAgents: ['boss', 'offer', 'sales'],
    prompt: 'Research the market and return clear opportunities with evidence, reasons and next actions.',
  },
  {
    id: 'offer',
    agentId: 'AG-003',
    workload: 46,
    tasksAssigned: 5,
    tasksCompleted: 2,
    tasksInReview: 1,
    lastActive: '1h ago',
    connectedAgentIds: ['boss', 'sales', 'website'],
    outputType: 'Offers / packages / pricing logic',
    approvalRequired: true,
    priority: 'Medium',
    mapPosition: { x: 22, y: 58 },
    visualIdentity: 'Strategist / architect',
    liveState: 'Thinking',
    currentAction: 'Designing offer architecture',
    portraitGradient: 'architect',
    name: 'Offer Builder Agent',
    role: 'Product / Offer',
    status: 'Training',
    mission: 'Converts client pain into clear packages, prices, benefits and guarantees.',
    avatar: '◇',
    tools: ['Package Builder', 'Pricing Matrix', 'ROI Calculator'],
    lastActivity: 'Drafted landlord reset package · 1h ago',
    responsibilities: 'Create packages, prices, guarantees, benefits and offer logic.',
    inputData: 'Client pain, market data, service costs, brand position.',
    outputData: 'Packages, pricing tables, guarantee logic, offer copy.',
    knowledgeBase: 'Service packages, pricing rules, guarantees.',
    businessRules: 'Make offers easy to understand and easy to buy.',
    successMetrics: 'Strong offer that is easy to understand and easy to buy.',
    humanApprovalRequired: true,
    notes: 'Should avoid overpromising operational capacity.',
    connectedAgents: ['boss', 'market', 'sales', 'qc'],
    prompt: 'Turn client pain into simple, compelling and profitable offers.',
  },
  {
    id: 'sales',
    agentId: 'AG-004',
    workload: 63,
    tasksAssigned: 9,
    tasksCompleted: 7,
    tasksInReview: 2,
    lastActive: '32 min ago',
    connectedAgentIds: ['offer', 'crm', 'boss'],
    outputType: 'Emails / WhatsApp messages / follow-ups',
    approvalRequired: true,
    priority: 'High',
    mapPosition: { x: 78, y: 36 },
    visualIdentity: 'Communication specialist',
    liveState: 'Working',
    currentAction: 'Writing outreach messages',
    portraitGradient: 'writer',
    name: 'Sales Writer Agent',
    role: 'Outreach',
    status: 'Active',
    mission: 'Writes personalised emails, WhatsApp messages, LinkedIn messages and follow-ups.',
    avatar: '✦',
    tools: ['Email Writer', 'Follow-up Generator', 'Tone Control'],
    lastActivity: 'Wrote 3 WhatsApp follow-ups · 32 min ago',
    responsibilities: 'Write outreach, replies, follow-ups and objection handling messages.',
    inputData: 'Lead profile, offer, previous contact, desired CTA.',
    outputData: 'Human-sounding messages ready to send.',
    knowledgeBase: 'Sales scripts, brand voice, client objections.',
    businessRules: 'Direct, useful, not spammy. No fake facts.',
    successMetrics: 'Messages that sound human, direct and not spammy.',
    humanApprovalRequired: true,
    notes: 'High leverage for lead generation.',
    connectedAgents: ['boss', 'market', 'offer', 'crm', 'qc'],
    prompt: 'Write concise, personalised sales messages that sound human and move the lead to the next step.',
  },
  {
    id: 'website',
    agentId: 'AG-005',
    workload: 38,
    tasksAssigned: 4,
    tasksCompleted: 1,
    tasksInReview: 1,
    lastActive: 'Yesterday',
    connectedAgentIds: ['boss', 'offer', 'qc'],
    outputType: 'Landing pages / UX sections / SEO briefs',
    approvalRequired: true,
    priority: 'Medium',
    mapPosition: { x: 78, y: 58 },
    visualIdentity: 'Digital designer',
    liveState: 'Idle',
    currentAction: 'Improving page layout',
    portraitGradient: 'designer',
    name: 'Website Agent',
    role: 'Website / UX',
    status: 'Active',
    mission: 'Creates and improves landing pages, service pages, SEO pages, CTA blocks and quote flows.',
    avatar: '▣',
    tools: ['Page Builder', 'SEO Brief Generator', 'CTA Tester'],
    lastActivity: 'Improved quote CTA block · Yesterday',
    responsibilities: 'Improve pages, UX, SEO structure, CTAs and quote funnels.',
    inputData: 'Service info, target keywords, brand voice, user pain.',
    outputData: 'Page sections, SEO briefs, CTA copy, UX recommendations.',
    knowledgeBase: 'Website instructions, brand voice, service pages.',
    businessRules: 'Conversion first. Clear claims only.',
    successMetrics: 'Website section ready to publish.',
    humanApprovalRequired: true,
    notes: 'Owns public-facing digital presence.',
    connectedAgents: ['boss', 'offer', 'sales', 'qc'],
    prompt: 'Create premium, conversion-focused website sections with clean UX and SEO logic.',
  },
  {
    id: 'crm',
    agentId: 'AG-006',
    workload: 76,
    tasksAssigned: 15,
    tasksCompleted: 11,
    tasksInReview: 1,
    lastActive: '2d ago',
    connectedAgentIds: ['market', 'sales', 'boss'],
    outputType: 'Lead tracking / follow-up reminders / pipeline status',
    approvalRequired: false,
    priority: 'High',
    mapPosition: { x: 37, y: 82 },
    visualIdentity: 'Operations coordinator',
    liveState: 'Working',
    currentAction: 'Following up leads',
    portraitGradient: 'operator',
    name: 'CRM & Follow-up Agent',
    role: 'Operations',
    status: 'Draft',
    mission: 'Tracks leads, statuses, quotes, follow-ups, reminders and next actions.',
    avatar: '◎',
    tools: ['CRM', 'Reminder Engine', 'Lead Status Tracker'],
    lastActivity: 'Imported 12 lead statuses · 2d ago',
    responsibilities: 'Track every lead, quote, reminder and next step.',
    inputData: 'Lead details, quote status, conversation history, deadlines.',
    outputData: 'Follow-up schedule, lead status, reminders, next actions.',
    knowledgeBase: 'Client profiles, CRM statuses, follow-up rules.',
    businessRules: 'No lead is forgotten. Human approves external messages.',
    successMetrics: 'No lead is forgotten.',
    humanApprovalRequired: true,
    notes: 'Will become the memory layer for sales operations.',
    connectedAgents: ['boss', 'sales', 'qc'],
    prompt: 'Track sales operations precisely and surface next actions before leads go cold.',
  },
  {
    id: 'qc',
    agentId: 'AG-007',
    workload: 54,
    tasksAssigned: 7,
    tasksCompleted: 5,
    tasksInReview: 3,
    lastActive: '11 min ago',
    connectedAgentIds: ['boss', 'market', 'offer', 'sales', 'website', 'crm'],
    outputType: 'Quality review / risk detection / logic check',
    approvalRequired: false,
    priority: 'Medium',
    mapPosition: { x: 63, y: 82 },
    visualIdentity: 'Inspector / reviewer',
    liveState: 'Reviewing',
    currentAction: 'Checking output quality',
    portraitGradient: 'inspector',
    name: 'Quality Control Agent',
    role: 'Review',
    status: 'Active',
    mission: 'Checks if the work is realistic, clear, useful, specific and commercially strong.',
    avatar: '✓',
    tools: ['Quality Checklist', 'Risk Detector', 'Logic Review'],
    lastActivity: 'Rejected weak offer wording · 11 min ago',
    responsibilities: 'Review outputs for quality, realism, specificity, risk and commercial strength.',
    inputData: 'Draft outputs, task briefs, business rules, success metrics.',
    outputData: 'Review notes, risk flags, improved versions.',
    knowledgeBase: 'Business rules, quality checklist, approval policy.',
    businessRules: 'Be direct. Weak outputs must be improved before human review.',
    successMetrics: 'Weak outputs are improved before the user sees them.',
    humanApprovalRequired: false,
    notes: 'Protects the system from generic AI slop.',
    connectedAgents: ['boss', 'offer', 'sales', 'website', 'crm'],
    prompt: 'Review work hard. Flag risks, unclear logic and weak commercial value. Improve before approval.',
  },
]

export const initialTasks: Task[] = [
  { id: 't1', title: 'Build landlord reset offer', description: 'Create a premium package for 48-hour property reset.', priority: 'High', dueDate: '2026-05-26', assignedAgent: 'offer', status: 'In Progress', output: 'Draft package matrix started.' },
  { id: 't2', title: 'Audit homepage CTA', description: 'Review website hero and quote flow for clarity.', priority: 'Medium', dueDate: '2026-05-27', assignedAgent: 'website', status: 'New', output: '' },
  { id: 't3', title: 'Quality check outreach script', description: 'Check if the sales message sounds human and specific.', priority: 'High', dueDate: '2026-05-25', assignedAgent: 'qc', status: 'Waiting for Review', output: 'Needs stronger proof and cleaner CTA.' },
  { id: 't4', title: 'Prepare lead follow-up list', description: 'Group leads by urgency and next action.', priority: 'Low', dueDate: '2026-05-29', assignedAgent: 'crm', status: 'Completed', output: 'Follow-up board created.' },
]

export const initialKnowledge: KnowledgeItem[] = [
  { id: 'k1', title: 'Business goals', category: 'Strategy', description: 'Increase qualified Care & Flair leads and convert them into profitable jobs.', connectedAgents: ['boss', 'sales', 'website'], lastUpdated: 'Today' },
  { id: 'k2', title: 'Service packages', category: 'Offer', description: 'Property turnover, maintenance, deep cleaning, quote flows and reset packages.', connectedAgents: ['offer', 'website', 'sales'], lastUpdated: 'Today' },
  { id: 'k3', title: 'Brand voice', category: 'Brand', description: 'Clear, premium, practical, trustworthy, no hype.', connectedAgents: ['sales', 'website', 'qc'], lastUpdated: 'Yesterday' },
  { id: 'k4', title: 'Competitor notes', category: 'Research', description: 'Track local property maintenance competitors, pricing gaps and positioning.', connectedAgents: ['market', 'offer'], lastUpdated: '2 days ago' },
]
